### ISSUE TITLE
Error al ejecutar yarn en OSX

### ISSUE THREAD

**Issue by Graywolf9** [seagomezar/workshopJsconfmxRNApp#4]
fatal: unable to access 'http://ikt.pm2.io/ikt.git/': Could not resolve host: ikt.pm2.io

**Comment by seagomezar** [comment]
yarn -v                                                     
>>1.22.10

**Comment by aerda** [comment]
Pm2 es un manejador de procesos!!! Lo turned instalado?

**Comment by Graywolf9** [comment]
Pruebo con esa versión, tengo la 1.22.15

**Comment by Graywolf9** [comment]
Desde cero y con npm run start si corrió
